# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Su ultimo prestamo fue aprobado?'),
        ),
        migrations.AlterField(
            model_name='match',
            name=b'end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name=b'owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to='players.Player'),
        ),
    ]
