# Generated by Django 2.2.1 on 2020-07-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190817_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='active',
        ),
        migrations.AlterField(
            model_name='match',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_matches', to='players.PlayerProfile'),
        ),
    ]
