# Generated by Django 2.2.1 on 2021-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20200710_2011'),
        ('matches', '0003_auto_20200710_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='players.PlayerProfile'),
        ),
    ]
