# Generated by Django 2.2.1 on 2019-07-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('cell_phone', models.CharField(max_length=40)),
                ('real_full_name', models.CharField(max_length=60)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('locality', models.TextField(blank=True, default='', null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('province', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
