# Generated by Django 2.2.1 on 2020-07-10 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190817_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='province',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='real_full_name',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 7, 10, 19, 7, 44, 133781), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='surname',
            field=models.CharField(default='juan', max_length=50),
            preserve_default=False,
        ),
    ]
