# Generated by Django 2.2.1 on 2020-07-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200710_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(default='user_test', max_length=50),
            preserve_default=False,
        ),
    ]
