# Generated by Django 2.2.1 on 2020-07-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20200710_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
